In [1]:
import os, sys
import pandas as pd
os.getcwd()

'c:\\TREE\\UNI\\VI\\THLEP ERGASIA\\data'

In [2]:
df = pd.read_csv("data.csv")
df

        Count Modulation  Phase_Noise  IQ_Imbalance  Interference  SNR_Range
0           1   128-APSK         0.00          0.00           0.0          5
1           2   128-APSK         0.00          0.00           0.0          5
2           3   128-APSK         0.00          0.00           0.0          5
3           4   128-APSK         0.00          0.00           0.0          5
4           5   128-APSK         0.00          0.00           0.0          5
...       ...        ...          ...           ...           ...        ...
207917    918     16-QAM         0.08          0.15           0.2         15
207918    919     16-QAM         0.08          0.15           0.2         15
207919    920     16-QAM         0.08          0.15           0.2         15
207920    921     16-QAM         0.08          0.15           0.2         15
207921    922     16-QAM         0.08          0.15           0.2         15

[207922 rows x 6 columns]

In [ ]:
#df.info()

df[df["Modulation"] == "32-APSK"]

       Count Modulation  Phase_Noise  IQ_Imbalance  Interference  SNR_Range
24000      1    64-APSK         0.00          0.00           0.0          5
24001      2    64-APSK         0.00          0.00           0.0          5
24002      3    64-APSK         0.00          0.00           0.0          5
24003      4    64-APSK         0.00          0.00           0.0          5
24004      5    64-APSK         0.00          0.00           0.0          5
...      ...        ...          ...           ...           ...        ...
47995    996    64-APSK         0.08          0.15           0.2         25
47996    997    64-APSK         0.08          0.15           0.2         25
47997    998    64-APSK         0.08          0.15           0.2         25
47998    999    64-APSK         0.08          0.15           0.2         25
47999   1000    64-APSK         0.08          0.15           0.2         25

[24000 rows x 6 columns]